version: '3.8'

services:
#  nginx:
#     image: nginx:alpine
#     restart: always
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/sites-enabled/nginx.conf:/etc/nginx/conf.d/default.conf
#       - /home/ubuntu/log/nginx/:/var/log/nginx/
#     restart: always
#     stdin_open: true
#     tty: true
#     networks:
#       - app-network

 node-sails-boilerplate:  
  image: node-sails-boilerplate
  restart: always
  ports:
    - 1337
  environment:
    NEW_RELIC_LICENSE_KEY: 
    NEW_RELIC_APP_NAME: 
#     url: https://DOMAIN.COM
    #url: http://localhost
  networks:
      - app-network

networks:
  app-network:
    driver: bridge

